# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_busker_busker_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busker',
            name='busker_name',
        ),
    ]
