# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_busker_busker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='busker',
            name='busker_name',
            field=models.CharField(default='John', max_length=100),
            preserve_default=False,
        ),
    ]
