# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_busker_busker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_duration',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2),
        ),
    ]
