# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event_event_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='busker',
        ),
        migrations.RemoveField(
            model_name='following',
            name='user',
        ),
        migrations.RemoveField(
            model_name='busker',
            name='user',
        ),
        migrations.AddField(
            model_name='busker',
            name='email',
            field=models.CharField(default='johnsmith@hyperglobomega.net', max_length=100),
        ),
        migrations.DeleteModel(
            name='Following',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
