# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160730_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='busker',
            name='pw_hash',
            field=models.CharField(default='e68a95aadb0c73dfd968513174de4ddf', max_length=30),
        ),
    ]
