# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160802_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busker',
            name='pw_hash',
            field=models.CharField(default='', max_length=32),
        ),
    ]
